---
- hosts: 127.0.0.1
  connection: local
  become: yes

  tasks:

  - name: download iso , using https://tb.rg-adguard.net/
    get_url:
      url: https://tb.rg-adguard.net/dl.php?go=659a4291
      dest: /var/lib/libvirt/images/Win10_20H2_v2_English_x64.iso
      mode: '0755'

  - name: delete disket if exist
    file:
      state: absent
      path: "/var/lib/libvirt/images/audit_mode_unattend.img"

  - name: create disket
    shell: mkfs.msdos -C /var/lib/libvirt/images/audit_mode_unattend.img 1440

  - name: create a directory /media/floppy , if it does not exist
    ansible.builtin.file:
      path: /media/floppy
      state: directory
      mode: '0755'

  - name: mount
    shell: mount -o loop /var/lib/libvirt/images/audit_mode_unattend.img /media/floppy/
    
  - name: download autounattend.xml 
    get_url:
      url: https://raw.githubusercontent.com/vaal1988/windows_desktop/main/unattend/audit_mode.xml
      dest: /media/floppy/autounattend.xml 
      mode: '0755'

  - name: ummount
    shell: umount /media/floppy/

  - name: install vm 
    shell: |
      virt-install \
      --hvm --graphics vnc \
      --name win10 --os-variant win10 \
      --vcpu 2 --ram 4096 \
      --disk path=/var/lib/libvirt/images/win10.qcow2,size=70 \
      --disk path=/var/lib/libvirt/images/audit_mode_unattend.img,device=floppy \
      --cdrom=/var/lib/libvirt/images/Win10_20H2_v2_English_x64.iso \
      --network network=default \
      --boot hd,cdrom --noautoconsole

  - name: loop until win10 vm will be stopped during install
    virt:
      name: win10
      command: status
    register: win10_status
    until: win10_status.status == "shutdown"
    retries: 10
    delay: 120

  - name: show win10 vm status                 
    debug:
      msg: "{{ win10_status }}"

  - name: start win10
    virt:
      name: win10
      state: running

  - pause:
      minutes: 10

  - name: get ip of win10 vm
    shell: virsh domifaddr win10 | grep ipv4 | awk  '{print $4}' | sed -r 's/\/.+//'
    register: win10ip

  - name: show win10 ip                 
    debug:
      msg: "{{ win10ip.stdout }}"

- hosts: 127.0.0.1
  vars:
    ansible_host: "{{ win10ip.stdout }}"
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: ntlm
    ansible_winrm_scheme: https
    ansible_user: Admin
    ansible_password: password

  tasks:

  - name: wait for system to become reachable over WinRM
    wait_for_connection:
      delay: 300
      sleep: 20
      timeout: 900

  - name: ping
    win_ping:
