- name: Change default KeyboardLayoutPreload for new users
  win_regedit:
    path: HKLM:\ANSIBLE\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce
    name: LanguageList
    data: powershell.exe -command "Set-WinUserLanguageList -LanguageList en-US, ru, uk -Force"
    type: string
    state: present
    hive: C:\Users\Default\NTUSER.dat
