- name: Download LayoutModification.xml
  win_get_url:
    url: https://raw.githubusercontent.com/vaal1988/windows_desktop/main/layoutmodification/LayoutModification.xml
    dest: C:\Users\Default\AppData\Local\Microsoft\Windows\Shell\LayoutModification.xml

- name: Change default StartLayout for new users
  win_regedit:
    path: HKLM:\ANSIBLE\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce
    name: LanguageList
    data: powershell.exe -command "Import-StartLayout -layoutpath C:\Users\Default\AppData\Local\Microsoft\Windows\Shell\LayoutModification.xml -Mountpath C:\"
    type: string
    state: present
    hive: C:\Users\Default\NTUSER.dat

- name: NoPinningStoreToTaskbar
  win_regedit:
    path: HKLM:\ANSIBLE\Software\Policies\Microsoft\Windows\Explorer
    name: NoPinningStoreToTaskbar
    data: 1
    type: dword
    state: present
    hive: C:\Users\Default\NTUSER.dat
