# OneDrive Standalone Update Task

- name: OneDrive Task
  win_shell: Get-ScheduledTask -TaskName 'OneDrive Standalone Update*' | Disable-ScheduledTask

# Save documents to OneDrive by default

- name: DisableLibrariesDefaultSaveToOneDrive
  win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\OneDrive
    name: DisableLibrariesDefaultSaveToOneDrive
    data: 0
    type: dword

# Remove OneDrive Icon from Navigation Pane

- name: DisableWindowsSpotlightFeatures
  win_regedit:
    path: 'HKLM:\DEFAULT\Software\Classes\CLSID{018D5C66-4533-4307-9B53-224DE2ED1FE6}'
    name: System.IsPinnedToNameSpaceTree
    data: 0
    type: dword

- name: DisableWindowsSpotlightFeatures Wow6432Node
  win_regedit:
    path: 'HKLM:\DEFAULT\Software\Classes\Wow6432Node\CLSID{018D5C66-4533-4307-9B53-224DE2ED1FE6}'
    name: System.IsPinnedToNameSpaceTree
    data: 0
    type: dword

# Remove OneDrive setup

- name: Remove OneDrive Run
  win_regedit:
    path: HKLM:\DEFAULT\Software\Microsoft\Windows\CurrentVersion\Run
    name: OneDrive
    state: absent

- name: Remove OneDriveSetup Run
  win_regedit:
    path: HKLM:\DEFAULT\Software\Microsoft\Windows\CurrentVersion\Run
    name: OneDriveSetup
    state: absent